services:
  #PHP Service
  laravel_next:
    build:
      args:
        user: ahrasel
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel_next
    container_name: laravel_next
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_next_network

  #MySQL Service
  laravel_next_db:
    image: mysql:8.0
    container_name: laravel_next_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel_next}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-laravel_next}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel_next}
      MYSQL_USER: ${DB_USERNAME:-laravel_next}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel_next_mysql_data:/var/lib/mysql
    networks:
      - laravel_next_network

  #Nginx Service
  laravel_next_nginx:
    image: nginx:alpine
    container_name: laravel_next_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel_next_network
  # phpmyadmin service
  laravel_next_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: laravel_next_phpmyadmin
    depends_on:
      - laravel_next_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: laravel_next_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - laravel_next_network

  laravel_next_redis_cache:
    image: redis:alpine
    restart: always
    container_name: laravel_next_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-laravel_next}
    volumes:
      - laravel_next_cache:/data
    networks:
    - laravel_next_network

#Docker Networks
networks:
  laravel_next_network:
    driver: bridge
    name: laravel_next_network

#Volumes
volumes:
  laravel_next_mysql_data:
  laravel_next_cache:
